@startuml 123

' === цветовая схема по назначению ===
skinparam folderBackgroundColor<<root>>      White
skinparam folderBackgroundColor<<app>>       LightGreen
skinparam folderBackgroundColor<<deploy>>    LightSteelBlue
skinparam folderBackgroundColor<<github>>    LightSalmon
skinparam folderBackgroundColor<<data>>      LightYellow
skinparam folderBackgroundColor<<monitoring>> LightPink
skinparam folderBackgroundColor<<iac>>       PaleTurquoise

' === главный контейнер ===
folder "myapp" <<root>> {
  ' ---------- Слой приложения ----------
  folder "app" <<app>> {
    file "main.go"  as goMain
    file "main_test.go" as goTest
    folder "handlers"
    folder "models"
    file "go.mod"   as goMod
    file "go.sum"   as goSum

    note right of goMod
      Go 1.22
      chi v5
    end note
  }

  ' ---------- CI/CD ----------
  folder ".github" <<github>> {
    file "cicd.yml"   as cicd
  }

  ' ---------- Deploy ----------
  folder "deploy" <<deploy>> {
    folder "ansible" {
      file "README.md"
      file "ansible.cfg"
      file "requirements.yml"

      folder "inventory" {
        file "dev.yml"
        file "prod.yml"
      }



      folder "playbooks" {
        file "site.yml"      as site
        file "provision.yml" as provision
        file "deploy.yml"    as deployPlay
        file "cleanup.yml"
      }

      folder "roles" {
        folder "common"
        folder "docker" as dk
        folder "k8s-node"
        folder "k8s-cluster"
        folder "cert-manager"
        folder "ingress-nginx"
        folder "prometheus-stack" as prom <<monitoring>>
        folder "efk"
        folder "postgres-ha" as pg     <<data>>
        folder "redis"
        folder "myapp-role"
      }

      folder "group_vars" {
        file "all.yml"
        file "k8s_cluster.yml"
        file "myapp.yml"
      }

      folder "host_vars"
    }

    
    
    folder "terraform"  <<iac>>
    folder "helm"
    folder "docker" {
      file "Dockerfile"
    }
    folder "k8s"
    file "skaffold.yaml"
    file "docker-compose.yml"
  }

  ' ---------- Misc ----------
  file ".pre-commit-config.yaml"
  file "Taskfile.yml"
  file "requirements.txt"
  file "LICENSE"
  file "README.md"
}

' ---------- потоки и зависимости ----------
cicd --> site  : triggers
site --> provision : include
provision --> k8sCluster : apply
pg --> prom : expose metrics

cloud "Docker Hub"  as hub {
  folder "myapp:latest"
}
dk --> hub : push

' ---------- легенда ----------
legend right
  | Color | Layer      |
  |<#LightGreen>   App        |
  |<#LightSteelBlue> Deploy     |
  |<#LightSalmon>  GitHub CI  |
  |<#LightYellow>  Data       |
  |<#LightPink>    Monitoring |
  |<#PaleTurquoise> IaC        |
endlegend
@enduml