---
galaxy_info:
  author: devops
  description: common baseline
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags: ["common"]
dependencies: []