name: ci

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.22" }
      - run: go mod tidy
      - run: go test ./...
      - run: go build -o ../full-devops-stack .

  docker:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./app
          file: deploy/docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/full-devops-stack:latest

  cd:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy/ansible/playbooks/site.yml
          directory: .
          inventory: deploy/ansible/inventory/prod.yml
          key: ${{ secrets.SSH_KEY }}
          options: --extra-vars "image_tag=${{ github.ref_name }}"